### PR TITLE
Implement remove command

### PR DESCRIPTION
**Pull request by eugulixes**

### CODE REVIEW

**Review by denismosolov — COMMENTED** [review]
Let's stop docker containers before removing.

**Comment by denismosolov** [comment]
@eugulixes how about removing volumes?
single-note puts some data to `/srv/mongodb` and `/srv/postgres`

**Comment by eugulixes** [comment]
> @eugulixes how about removing volumes?
> single-note puts some data to `/srv/mongodb` and `/srv/postgres`

I think we have to put volumes to the build directory and remove the content of the directory, including volumes.

**Comment by denismosolov** [comment]
> > @eugulixes how about removing volumes?
> > single-note puts some data to `/srv/mongodb` and `/srv/postgres`
> 
> I think we have to put volumes to the build directory and remove the content of the directory, including volumes.

I agree, but for now let's remove `/srv/mongodb` and `/srv/postgres`. We can change that once move volumes to the build directory

**Comment by eugulixes** [comment]
@karpa4o4, @denismosolov, the volumes were moved from `/srv` to the build directory in the `ng` branch (see https://github.com/tolstoyevsky/cusdeb-single-node/pull/64). I'm merging the branch to the `ng` branch.

**Pull request merged**
